Fetching data from json file
imambux/comfy-house pull request #10
Opened 2022-03-22 14:59 UTC by SabaMallah

2022-03-22 15:01 UTC, SabaMallah commented
> @SabaMallah is this PR? Is it ready for review?
Yes , i have created the PR.

2022-03-22 15:26 UTC, imambux commented on app.js
> +  return (productsCenterDOM.innerHTML = results);
Hi @SabaMallah, I have a few concerns:
- What is it exactly that is returned by this function?
- Why are you returning anything at the first place if you are not using it?

2022-03-22 15:27 UTC, imambux commented on app.js
>  // get all products
please remove this comment

2022-03-22 15:28 UTC, imambux commented on app.js
> +getProducts();
Why do you need to call this function separately from a variable? If it's used just once you can call the function right away. e.g. function () {...}();

2022-03-22 15:31 UTC, imambux commented on app.js
> +// productsCenterDOM.innerHTML = fetch("products.json")
Is this comment going to be merged with main branch? As a standard, we should not have code in the main branch that is not being used. Please remove this comment.

2022-03-22 15:32 UTC, imambux commented on index.html
> +        <!-- <article class="product">
please remove the comments

2022-03-22 15:33 UTC, imambux requested changes
Please fix the concerns

2022-03-25 13:45 UTC, imambux approved these changes

2022-03-26 06:29 UTC, merged